# permissions for end users to view clusterproperties.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterproperty-viewer-role
rules:
- apiGroups:
  - about.k8s.io
  resources:
  - clusterproperties
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - about.k8s.io
  resources:
  - clusterproperties/status
  verbs:
  - get
