# permissions for end users to edit clusterproperties.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterproperty-editor-role
rules:
- apiGroups:
  - about.k8s.io
  resources:
  - clusterproperties
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - about.k8s.io
  resources:
  - clusterproperties/status
  verbs:
  - get
